### ISSUE TITLE
HDTV or 720p?

### ISSUE THREAD

**Issue by ghost** [wspi/eztv-downloader#1]
Hello,

First, let me thank you for this script. I was about to start writing a similar one before I stumbled upon yours. I got it working very easily, so props to you!

Here's my question. What happens when eztv releases both 720p and HDTV for the same episode? I guess whichever comes first is downloaded, the shows file gets updated and the other release is skipped. Correct me if that's wrong.

Most of the time HDTV is realeased prior to 720p, so that means no 720p with the script. What would be the best way to implement a 720p-only option? I might try to add it myself ;-)

Cheers

**Comment by wspi** [comment]
Hello,

thanks for the feedback :)

I'm glad it was easy and useful for you.

Yes, it gets the first link it finds, I was trying to implement a way of choosing the quality, but eztv doesn't give this info in a easy way to be parsed, only in ezrss but this tool is always unavailable and not updated with the episodes as fast as the main website, usually with more than a day of delay :(

If you have any idea on how to get this info from eztv I'll add it for sure!

By now the only way to "solve" this, is running this script after the 720p is released. Imagine that you tv show is released at 10pm, you could add the script in the cron, let's say to 11pm, that time the 720p release is probably available and will be used.

Thanks

**Comment by wspi** [comment]
solved by guigui-benmaurice
